### ISSUE TITLE
Why does an input file of  the predict model require a label columns?

### ISSUE THREAD

**Issue by RysBen** [Freshwind-Bioinformatics/TABR-BERT#3]
Dear developer,

The below was some content from README.md:

```
Usage: predict_tcr_pmhc_binding.py [options]
Required:
      --input STRING: The data to be predicted (*.csv) 
                      Required columns: ["allele", "peptide", "cdr3"]
```

When I used an input files with three columns ("allele", "peptide", "cdr3"), some error happened:
```
Traceback (most recent call last):
  File "/.../predict_tcr_pmhc_binding.py", line 199, in <module>
    labels = input_df["label"].tolist()
  File "/.../envs/tabr_bert/lib/python3.9/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/.../envs/tabr_bert/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'label'
```

So why does an input file of  the predict model require a label column?

Thanks,
Ben

**Comment by RysBen** [comment]
Sorry, I forgot I cancel annotation of the label line  ⊙︿⊙
